import { StyleSheet } from 'react-native';

export const exploreStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f172a',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0f172a',
  },
  loadingText: {
    color: '#94a3b8',
    marginTop: 12,
    fontSize: 14,
    fontWeight: '600',
  },
  centerContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  lockCircle: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: '#fbbf2415',
    borderWidth: 1,
    borderColor: '#fbbf2433',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  headerText: {
    fontSize: 22,
    fontWeight: '900',
    color: '#f8fafc',
    textAlign: 'center',
    marginBottom: 10,
  },
  descText: {
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 32,
  },
  btnSync: {
    backgroundColor: '#1e293b',
    borderWidth: 1,
    borderColor: '#334155',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 14,
  },
  btnSyncText: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '800',
  },
  scrollContainer: {
    padding: 20,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#f8fafc',
  },
  headerDesc: {
    fontSize: 13,
    color: '#94a3b8',
    lineHeight: 18,
    marginBottom: 24,
  },
  metricsWrapper: {
    gap: 12,
    marginBottom: 24,
  },
  metricCard: {
    backgroundColor: '#1e293b',
    borderWidth: 1,
    borderColor: '#334155',
    borderRadius: 18,
    padding: 16,
  },
  metricRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  metricTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metricName: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '800',
  },
  metricVal: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '700',
  },
  progressBackground: {
    height: 8,
    backgroundColor: '#0f172a',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#f8fafc',
    marginBottom: 12,
    marginTop: 10,
  },
  nodeCard: {
    backgroundColor: '#1e293b',
    borderWidth: 1,
    borderColor: '#334155',
    borderRadius: 18,
    paddingHorizontal: 16,
  },
  nodeItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
  },
  nodeName: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '800',
  },
  nodeDesc: {
    color: '#94a3b8',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  nodeDivider: {
    height: 1,
    backgroundColor: '#334155',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  detailCard: {
    backgroundColor: '#1e293b',
    borderWidth: 1,
    borderColor: '#334155',
    borderRadius: 20,
    padding: 18,
    marginBottom: 20,
  },
  detailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  detailName: {
    fontSize: 18,
    fontWeight: '900',
    color: '#f8fafc',
  },
  detailBlock: {
    fontSize: 12,
    color: '#60a5fa',
    fontWeight: '700',
    marginTop: 2,
  },
  gapBadge: {
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  gapBadgeText: {
    fontSize: 11,
    fontWeight: '800',
  },
  populationText: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 14,
  },
  detailDivider: {
    height: 1,
    backgroundColor: '#334155',
    marginBottom: 14,
  },
  gapMetricsRow: {
    gap: 12,
  },
  gapMetricItem: {
    gap: 6,
  },
  metricLabel: {
    color: '#94a3b8',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  barContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  barPercentage: {
    color: '#f8fafc',
    fontSize: 12,
    fontWeight: '800',
    width: 32,
    textAlign: 'right',
  },
  villageGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
  },
  villageChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1e293b',
    borderWidth: 1,
    borderColor: '#334155',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    margin: 4,
  },
  villageChipActive: {
    borderColor: '#3b82f6',
    backgroundColor: '#3b82f61a',
  },
  villageIndicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 8,
  },
  villageChipText: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '700',
  },
  villageChipTextActive: {
    color: '#3b82f6',
  },
});
